/**
 * Rankings page: renders a published snapshot (rank, rating, SoS,
 * confidence, per-game weight explanations) computed by @scorebot/rankings.
 */
import type { Snapshot, SnapshotTeam } from '@scorebot/rankings';
// Snapshot JSON is generated by the rankings pipeline; the fixture stands in
// until full-season snapshots publish through the same path.
import fixture from './rankings/snapshot-boys-fixture.json';

const snapshot = fixture as unknown as Snapshot;

function statusOf(t: SnapshotTeam): string {
  if (t.rank == null) return 'JV';
  return t.qualified ? 'Ranked' : `Provisional (${t.qualificationReason})`;
}

function renderMeta(): void {
  const m = snapshot.meta;
  const el = document.getElementById('rankings-meta')!;
  el.textContent =
    `${m.season} · ${m.division} · ${m.totalGames} games (${m.ratedGames} rated, ${m.ignoredGames} ignored) · ` +
    `results through ${m.resultsThrough} · converged in ${m.iterations} iterations`;
  document.getElementById('ruleset-version')!.textContent = m.rulesetVersion;
}

function renderTable(): void {
  const body = document.getElementById('rankings-body')!;
  body.innerHTML = '';
  for (const t of snapshot.teams) {
    const tr = document.createElement('tr');
    tr.dataset.team = t.id;
    const cells = [
      t.rank ?? '—',
      t.name,
      t.rating.toFixed(1),
      `${t.wins}-${t.losses}${t.ties ? `-${t.ties}` : ''}`,
      `${t.sos.toFixed(0)} (${t.sosPercentile})`,
      t.sd == null ? t.confidence : `${t.confidence} ±${t.sd.toFixed(1)}`,
      statusOf(t),
    ];
    for (const c of cells) {
      const td = document.createElement('td');
      td.textContent = String(c);
      tr.appendChild(td);
    }
    tr.addEventListener('click', () => showTeam(t.id));
    body.appendChild(tr);
  }
}

function showTeam(id: string): void {
  const t = snapshot.teams.find((x) => x.id === id);
  if (!t) return;
  document.getElementById('rankings-view')!.classList.add('hidden');
  document.getElementById('team-view')!.classList.remove('hidden');
  document.getElementById('team-name')!.textContent = t.name;
  document.getElementById('team-summary')!.textContent =
    `Rating ${t.rating.toFixed(1)} · ${t.wins}-${t.losses} (counted) · ` +
    `SoS ${t.sos.toFixed(1)} (p${t.sosPercentile}) · confidence ${t.confidence} · ${statusOf(t)}`;
  const body = document.getElementById('team-games-body')!;
  body.innerHTML = '';
  for (const g of t.games) {
    const tr = document.createElement('tr');
    if (g.ignored) tr.classList.add('ignored');
    const cells = [
      g.opponentName,
      `${g.result} ${g.scoreFor}-${g.scoreAgainst}`,
      g.gameRating.toFixed(1),
      (g.effect >= 0 ? '+' : '') + g.effect.toFixed(1),
      `${g.scoreWeight.toFixed(2)}/${g.dateWeight.toFixed(2)}/${g.seriesMultiplier.toFixed(1)}`,
      g.ignored ? `ignored (${g.ignoreReason})` : 'counted',
    ];
    for (const c of cells) {
      const td = document.createElement('td');
      td.textContent = String(c);
      tr.appendChild(td);
    }
    body.appendChild(tr);
  }
}

function showRankings(): void {
  document.getElementById('team-view')!.classList.add('hidden');
  document.getElementById('rankings-view')!.classList.remove('hidden');
}

document.getElementById('back-link')!.addEventListener('click', (e) => {
  e.preventDefault();
  showRankings();
});

renderMeta();
renderTable();
